/**
 * gitignore-gen.js
 * ─────────────────────────────────────────────────────────────
 * Every run does a clean slate:
 *   1. Deletes the existing .gitignore (if any)
 *   2. Deletes ALL *.stub files found anywhere in the tree
 *   3. Scans every file recursively for files > threshold MB
 *   4. Writes a fresh .gitignore with those files listed
 *   5. Creates a <filename>.stub next to each oversized file
 *
 * Usage:
 *   node gitignore-gen.js 95     ← threshold = 95 MB
 *   node gitignore-gen.js 50     ← threshold = 50 MB
 *   node gitignore-gen.js        ← defaults to 100 MB
 *
 * No external dependencies — Node.js built-ins only.
 * ─────────────────────────────────────────────────────────────
 */

const fs   = require('fs');
const path = require('path');

// ── Config ────────────────────────────────────────────────────
const ROOT        = process.cwd();
const SCRIPT_NAME = path.basename(__filename);
const GITIGNORE   = path.join(ROOT, '.gitignore');
const SKIP_DIRS   = new Set(['.git', 'node_modules', '.svn', '.hg']);

const RAW_ARG      = process.argv[2];
const THRESHOLD_MB = RAW_ARG ? parseFloat(RAW_ARG) : 100;

if (isNaN(THRESHOLD_MB) || THRESHOLD_MB <= 0) {
  console.error(`\n❌  Invalid threshold: "${RAW_ARG}". Pass a positive number in MB.\n`);
  console.error(`    Example: node ${SCRIPT_NAME} 95\n`);
  process.exit(1);
}

const THRESHOLD_BYTES = THRESHOLD_MB * 1024 * 1024;

// ── Helpers ───────────────────────────────────────────────────
const toMB      = (b) => (b / 1024 / 1024).toFixed(2);
const toGB      = (b) => (b / 1024 / 1024 / 1024).toFixed(3);
const toGitPath = (p) => path.relative(ROOT, p).replace(/\\/g, '/');

function humanSize(bytes) {
  if (bytes >= 1073741824) return `${toGB(bytes)} GB`;
  if (bytes >= 1048576)    return `${toMB(bytes)} MB`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

// ── Walk — collect oversized files AND all stub files ─────────
function walkDir(dir, oversized = [], stubs = []) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch { return { oversized, stubs }; }

  for (const entry of entries) {
    if (entry.name === SCRIPT_NAME  && dir === ROOT) continue; // skip self
    if (entry.name === '.gitignore' && dir === ROOT) continue; // handle separately

    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walkDir(full, oversized, stubs);
    } else if (entry.isFile()) {
      // collect stubs for deletion regardless of size
      if (entry.name.endsWith('.stub')) {
        stubs.push(full);
        continue;
      }

      try {
        const stat = fs.statSync(full);
        if (stat.size > THRESHOLD_BYTES) {
          oversized.push({
            full,
            size    : stat.size,
            name    : entry.name,
            ext     : path.extname(entry.name),
            modified: stat.mtime.toISOString(),
          });
        }
      } catch { /* permission denied — skip */ }
    }
  }

  return { oversized, stubs };
}

// ── Build stub content ────────────────────────────────────────
function buildStub(file) {
  const gitPath = toGitPath(file.full);
  return [
    `STUB`,
    ``,
    `This is a placeholder for a file excluded from this repository`,
    `because it exceeds the ${THRESHOLD_MB} MB size threshold for plain Git.`,
    ``,
    `  File name : ${file.name}`,
    `  File path : ${gitPath}`,
    `  File size : ${humanSize(file.size)} (${file.size.toLocaleString()} bytes)`,
    `  Extension : ${file.ext || '(none)'}`,
    `  Modified  : ${file.modified}`,
    `  Excluded  : files > ${THRESHOLD_MB} MB (gitignore-gen.js)`,
    ``,
    `To obtain the original file, contact the repository owner`,
    `or regenerate it from source.`,
  ].join('\n');
}

// ── Build .gitignore content ──────────────────────────────────
function buildGitignore(oversized) {
  const timestamp = new Date().toLocaleString();
  const lines = [
    `# ── Generated by gitignore-gen.js ──────────────────────────`,
    `# ── Threshold : > ${THRESHOLD_MB} MB                                    `,
    `# ── Generated : ${timestamp}              `,
    `# ── Files     : ${oversized.length} excluded                            `,
    `# ─────────────────────────────────────────────────────────────`,
    ``,
    `# Script itself`,
    `${SCRIPT_NAME}`,
    ``,
    `# Oversized files (> ${THRESHOLD_MB} MB)`,
  ];

  for (const f of oversized) {
    lines.push(`${f.gitPath}   # ${humanSize(f.size)}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ── Step 1: Wipe .gitignore ───────────────────────────────────
function wipeGitignore() {
  if (fs.existsSync(GITIGNORE)) {
    fs.unlinkSync(GITIGNORE);
    return true;
  }
  return false;
}

// ── Step 2: Delete all stubs ──────────────────────────────────
function wipeStubs(stubs) {
  let deleted = 0;
  let failed  = 0;
  for (const stubPath of stubs) {
    try {
      fs.unlinkSync(stubPath);
      deleted++;
    } catch {
      failed++;
    }
  }
  return { deleted, failed };
}

// ── Main ──────────────────────────────────────────────────────
function main() {
  const divider = '─'.repeat(65);

  console.log(`\n🚀  gitignore-gen.js — threshold: > ${THRESHOLD_MB} MB`);
  console.log(`    Root: ${ROOT}\n`);
  console.log(divider);

  // ── PHASE 1: Scan first (need stub list before wiping) ───────
  console.log(`\n🔍  Scanning tree...\n`);
  const { oversized, stubs } = walkDir(ROOT);
  oversized.sort((a, b) => b.size - a.size);

  console.log(`    Files > ${THRESHOLD_MB} MB : ${oversized.length}`);
  console.log(`    Stub files found   : ${stubs.length}`);

  // ── PHASE 2: Wipe .gitignore ──────────────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n🗑️   Wiping old .gitignore...`);
  const hadGitignore = wipeGitignore();
  console.log(hadGitignore ? `    ✅ Deleted` : `    ℹ️  None existed`);

  // ── PHASE 3: Wipe all stubs ───────────────────────────────────
  console.log(`\n🗑️   Deleting all *.stub files...`);
  if (stubs.length === 0) {
    console.log(`    ℹ️  None found`);
  } else {
    const { deleted, failed } = wipeStubs(stubs);
    for (const s of stubs) {
      console.log(`    ✖ ${path.relative(ROOT, s).replace(/\\/g, '/')}`);
    }
    console.log(`\n    Deleted: ${deleted}  |  Failed: ${failed}`);
  }

  if (oversized.length === 0) {
    // Write a minimal .gitignore with just the script itself
    fs.writeFileSync(GITIGNORE, buildGitignore([]), 'utf8');
    console.log(`\n${divider}`);
    console.log(`\n✅  No files exceed ${THRESHOLD_MB} MB.`);
    console.log(`    Fresh .gitignore written (script-only exclusion).\n`);
    return;
  }

  // ── PHASE 4: Write fresh .gitignore ──────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n📝  Writing fresh .gitignore...`);

  // attach gitPath to each file before writing
  for (const f of oversized) f.gitPath = toGitPath(f.full);

  fs.writeFileSync(GITIGNORE, buildGitignore(oversized), 'utf8');
  console.log(`    ✅ Written — ${oversized.length} entr${oversized.length === 1 ? 'y' : 'ies'}`);

  // ── PHASE 5: Create fresh stubs ───────────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n🗒️   Creating stub files...\n`);

  let stubsOk  = 0;
  let stubsFail = 0;

  for (const file of oversized) {
    const stubPath = file.full + '.stub';
    const relStub  = path.relative(ROOT, stubPath).replace(/\\/g, '/');
    try {
      fs.writeFileSync(stubPath, buildStub(file), 'utf8');
      const kb = (fs.statSync(stubPath).size / 1024).toFixed(2);
      console.log(`    📄 ${relStub}  [${kb} KB]`);
      stubsOk++;
    } catch (err) {
      console.warn(`    ⚠️  Failed: ${relStub} — ${err.message}`);
      stubsFail++;
    }
  }

  // ── Final summary ─────────────────────────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n📊  Summary:`);
  console.log(`    Threshold              : > ${THRESHOLD_MB} MB`);
  console.log(`    Old stubs deleted      : ${stubs.length}`);
  console.log(`    Files ignored          : ${oversized.length}`);
  console.log(`    New stubs created      : ${stubsOk}`);
  if (stubsFail) console.log(`    Stub creation failures : ${stubsFail}`);

  console.log(`\n💡  Next steps:`);
  console.log(`    git add .gitignore`);
  console.log(`    git add "**/*.stub"`);
  console.log(`    git commit -m "Ignore files over ${THRESHOLD_MB}MB, refresh stubs"`);
  console.log(`    git push\n`);
}

main();
